Repository zizmorcore/zizmor, pull requests merged in 2024-10, with the labels that each got.

#61 Fix typo: security -> securely
  docs/audit/dangerous-triggers.md
Labels: documentation

#74 docs: add homebrew install
  README.md
Labels: documentation

#75 fix: bump github-actions-models
  Cargo.lock
  Cargo.toml
Labels: bug

#78 feat: begin prepping zizmor's website
  .github/workflows/site.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  docs/DEVELOPMENT.md
  docs/assets/zizmor-demo.gif
  docs/audit/artipacked.md
  docs/audit/dangerous-triggers.md
  docs/audit/excessive-permissions.md
  docs/audit/hardcoded-container-credentials.md
  docs/audit/impostor-commit.md
  docs/audit/known-vulnerable-actions.md
  docs/audit/ref-confusion.md
  docs/audit/self-hosted-runner.md
  docs/audit/template-injection.md
  docs/audit/use-trusted-publishing.md
  docs/audits.md
  docs/development.md
  docs/index.md
  docs/installation.md
  docs/quickstart.md
  docs/usage.md
  mkdocs.yml
  site-requirements.txt
Labels: documentation

#83 fix: Always use the plain formatter even when the output is not a terminal
  src/main.rs
Labels: bugfix

#84 feat: show version
  src/main.rs
Labels: enhancement, cli

#92 Exclude `github.run_*` from template injection check
  src/audit/template_injection.rs
Labels: false-positive, bugfix

#95 fix(ci): move read permissions to job scope
  .github/workflows/zizmor.yml
Labels: bugfix
