Repository zizmorcore/zizmor, pull requests merged in 2024-12, with the labels that each got.

#220 test: snapshot tests
  Cargo.lock
  Cargo.toml
  docs/development.md
  tests/acceptance.rs
  tests/common.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__self_hosted-2.snap
  tests/snapshots/snapshot__self_hosted.snap
  tests/snapshots/snapshot__unpinned_uses-2.snap
  tests/snapshots/snapshot__unpinned_uses.snap
  tests/test-data/unpinned-uses.yml
Labels: tests

#221 test: refactor snapshot helper
  tests/snapshot.rs
Labels: tests

#223 docs: tweak installation layout
  docs/installation.md
Labels: documentation

#225 chore: add more metadata to Cargo.toml
  Cargo.toml
Labels: chore

#226 feat: add personas
  Cargo.lock
  Cargo.toml
  docs/snippets/help.txt
  docs/usage.md
  src/audit/artipacked.rs
  src/audit/github_env.rs
  src/audit/self_hosted_runner.rs
  src/audit/template_injection.rs
  src/audit/unpinned_uses.rs
  src/audit/use_trusted_publishing.rs
  src/finding/mod.rs
  src/main.rs
  src/models.rs
  src/registry.rs
  src/render.rs
  src/state.rs
  tests/acceptance.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__artipacked-2.snap
  tests/snapshots/snapshot__artipacked.snap
  tests/snapshots/snapshot__self_hosted-2.snap
  tests/snapshots/snapshot__unpinned_uses-2.snap
  tests/test-data/artipacked.yml
Labels: enhancement, cli

#228 chore: add thanks.dev to FUNDING
  .github/FUNDING.yml
Labels: chore

#229 chore: prep 0.7.0
  Cargo.lock
  Cargo.toml
Labels: chore

#230 feat: remote auditing
  Cargo.lock
  Cargo.toml
  Makefile
  docs/quickstart.md
  docs/snippets/help.txt
  docs/usage.md
  src/audit/github_env.rs
  src/audit/impostor_commit.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/ref_confusion.rs
  src/config.rs
  src/finding/mod.rs
  src/github_api.rs
  src/main.rs
  src/models.rs
  src/registry.rs
  src/render.rs
  src/sarif.rs
  src/state.rs
  src/utils.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__cant_retrieve.snap
  tests/snapshots/snapshot__conflicting_online_options-2.snap
  tests/snapshots/snapshot__conflicting_online_options-3.snap
  tests/snapshots/snapshot__conflicting_online_options.snap
Labels: enhancement, cli

#238 fix: template-injection: ignore issue/PR numbers
  src/audit/template_injection.rs
Labels: bugfix

#239 docs: restore search plugin
  mkdocs.yml
Labels: documentation

#241 ci: add a maturin matrix for PyPI releases
  .github/workflows/pypi.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  pyproject.toml
Labels: chore

#242 docs: document installing with PyPI
  docs/installation.md
Labels: documentation

#243 docs: add a trophy case
  docs/trophy-case.md
  mkdocs.yml
Labels: documentation

#246 fix: handle non-static env: in job steps
  Cargo.lock
  Cargo.toml
  src/audit/insecure_commands.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__insecure_commands-2.snap
  tests/snapshots/snapshot__insecure_commands.snap
  tests/test-data/insecure-commands.yml
Labels: bugfix

#232 refactor: experiment with tracing
  Cargo.lock
  Cargo.toml
  src/audit/artipacked.rs
  src/audit/dangerous_triggers.rs
  src/audit/excessive_permissions.rs
  src/audit/github_env.rs
  src/audit/hardcoded_container_credentials.rs
  src/audit/impostor_commit.rs
  src/audit/insecure_commands.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/mod.rs
  src/audit/ref_confusion.rs
  src/audit/self_hosted_runner.rs
  src/audit/template_injection.rs
  src/config.rs
  src/finding/locate.rs
  src/github_api.rs
  src/main.rs
  src/models.rs
  src/registry.rs
Labels: enhancement, refactor

#248 feat: remove --no-progress
  docs/snippets/help.txt
  src/main.rs
Labels: cli

#247 docs: update pre-commit docs to point to new repo
  .pre-commit-hooks.yaml
  docs/usage.md
Labels: documentation

#250 ci: use alls-green
  .github/workflows/ci.yml
Labels: chore

#252 ci: make zizmor.yml very fast with uvx
  .github/workflows/zizmor.yml
Labels: chore

#254 fix: template-injection: ignore another safe context
  src/audit/template_injection.rs
Labels: bugfix

#255 docs: switch GHA example to uvx
  docs/usage.md
Labels: documentation

#257 chore: Makefile: avoid a venv
  Makefile
Labels: chore

#259 docs: add template-injection tips
  docs/audits.md
Labels: documentation

#262 docs: update workflow name
  docs/usage.md
Labels: documentation, chore

#265 fix: download both .yml and .yaml from repos
  src/github_api.rs
Labels: bugfix

#266 docs: audits: add another env hacking reference
  docs/audits.md
Labels: documentation

#264 fix: bump annotate-snippets to fix crash
  Cargo.lock
  Cargo.toml
  tests/snapshots/snapshot__insecure_commands-2.snap
  tests/snapshots/snapshot__insecure_commands.snap
Labels: bugfix

#272 fix: move artipacked pendantic finding to auditor
  src/audit/artipacked.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__artipacked-3.snap
  tests/snapshots/snapshot__artipacked.snap
Labels: bugfix

#270 docs: Rename "unsecure" to insecure
  docs/audits.md
  docs/development.md
  tests/acceptance.rs
Labels: documentation

#273 docs: record more users of zizmor
  docs/trophy-case.md
Labels: documentation, chore

#274 feat: evaluates a matrix expansion only once
  src/audit/self_hosted_runner.rs
  src/models.rs
Labels: performance

#276 docs: more trophies
  docs/trophy-case.md
Labels: documentation

#277 fix: template-injection: ignore runner.temp
  src/audit/template_injection.rs
Labels: bugfix

#279 docs: make the trophy case prettier
  Makefile
  docs/development.md
  docs/snippets/render-trophies.py
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
  docs/trophy-case.md
Labels: documentation

#280 chore: prep 0.9.0
  Cargo.lock
  Cargo.toml
Labels: chore

#284 fix: dont crash when an expression does not expand a matrix
  src/audit/self_hosted_runner.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__self_hosted-8.snap
  tests/test-data/self-hosted/issue-283-repro.yml
Labels: bugfix

#285 chore: prep 0.9.1
  Cargo.lock
  Cargo.toml
Labels: chore

#287 docs: more trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#289 docs: more trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#292 docs: trophies, clean up install
  docs/installation.md
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#293 docs: fix emoji rendering
  mkdocs.yml
Labels: documentation, chore

#295 refactor: simplify use-trusted-publishing slightly
  src/audit/use_trusted_publishing.rs
  src/models.rs
Labels: refactor

#296 docs: more trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation

#297 fix: template-injection: consider runner.tool_cache safe
  src/audit/template_injection.rs
Labels: bugfix

#300 chore: prep 0.9.2
  Cargo.lock
  Cargo.toml
Labels: chore

#301 docs: update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#303 docs: support commits in trophy case
  docs/snippets/render-trophies.py
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation

#305 docs: Fix typo in development.md
  docs/development.md
Labels: documentation

#304 refactor: use http-cache for caching, optimize network calls
  Cargo.lock
  Cargo.toml
  docs/snippets/help.txt
  docs/usage.md
  src/audit/github_env.rs
  src/audit/impostor_commit.rs
  src/audit/ref_confusion.rs
  src/github_api.rs
  src/main.rs
  src/state.rs
Labels: performance, refactor

#227 feat: handle powershell in github-env audit
  Cargo.lock
  Cargo.toml
  src/audit/github_env.rs
Labels: enhancement

#309 fix: template-injection: more safe contexts
  src/audit/template_injection.rs
Labels: bugfix

#311 docs: add socials, copyright to footer
  mkdocs.yml
Labels: documentation, chore

#312 chore: remove FUNDING.yml
  .github/FUNDING.yml
Labels: chore

#314 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#315 ci: pin more workflows, enable rust-cache in tests
  .github/workflows/ci.yml
  .github/workflows/pypi.yml
  .github/workflows/site.yml
  .github/workflows/zizmor.yml
Labels: chore

#316 ci: disable wheel builds on pull_request
  .github/workflows/pypi.yml
Labels: chore

#317 fix: expands_to_static_values considers expressions inside strings
  src/models.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__template_injection-4.snap
  tests/test-data/template-injection/pr-317-repro.yml
Labels: bugfix

#323 docs: more trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#68 fix: sarif: add result and kind
  Cargo.lock
  Cargo.toml
  src/sarif.rs
Labels: bugfix

#326 fix: sarif: use ResultKind for kind
  src/sarif.rs
Labels: bugfix

#328 feat: add 'primary' locations
  src/audit/artipacked.rs
  src/audit/dangerous_triggers.rs
  src/audit/excessive_permissions.rs
  src/audit/github_env.rs
  src/audit/hardcoded_container_credentials.rs
  src/audit/impostor_commit.rs
  src/audit/insecure_commands.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/ref_confusion.rs
  src/audit/self_hosted_runner.rs
  src/audit/template_injection.rs
  src/audit/unpinned_uses.rs
  src/audit/use_trusted_publishing.rs
  src/finding/mod.rs
  src/models.rs
  src/sarif.rs
Labels: enhancement

#294 feat: initial cache-poisoning audit
  docs/audits.md
  src/audit/cache_poisoning.rs
  src/audit/mod.rs
  src/main.rs
  src/models.rs
  tests/acceptance.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__cache_poisoning-2.snap
  tests/snapshots/snapshot__cache_poisoning-3.snap
  tests/snapshots/snapshot__cache_poisoning-4.snap
  tests/snapshots/snapshot__cache_poisoning-5.snap
  tests/snapshots/snapshot__cache_poisoning-6.snap
  tests/snapshots/snapshot__cache_poisoning-7.snap
  tests/snapshots/snapshot__cache_poisoning-8.snap
  tests/snapshots/snapshot__cache_poisoning-9.snap
  tests/snapshots/snapshot__cache_poisoning.snap
  tests/test-data/cache-poisoning.yml
  tests/test-data/cache-poisoning/caching-disabled-by-default.yml
  tests/test-data/cache-poisoning/caching-enabled-by-default.yml
  tests/test-data/cache-poisoning/caching-opt-in-boolean-toggle.yml
  tests/test-data/cache-poisoning/caching-opt-in-boolish-toggle.yml
  tests/test-data/cache-poisoning/caching-opt-in-expression.yml
  tests/test-data/cache-poisoning/caching-opt-in-multi-value-toggle.yml
  tests/test-data/cache-poisoning/caching-opt-out.yml
  tests/test-data/cache-poisoning/no-cache-aware-steps.yml
  tests/test-data/cache-poisoning/workflow-tag-trigger.yml
Labels: enhancement, new-audit

#330 feat: Fix Sarif schema and add rules to Sarif files
  src/sarif.rs
Labels: enhancement

#332 chore: add a TODO
  src/sarif.rs
Labels: chore

#333 chore: prep 0.10.0
  Cargo.lock
  Cargo.toml
  docs/usage.md
Labels: chore

#335 Add GUAC to the trophy case
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#337 fix: excessive-permissions: be less noisy on one-job workflows
  src/audit/excessive_permissions.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__excessive_permissions-2.snap
  tests/snapshots/snapshot__excessive_permissions.snap
  tests/test-data/excessive-permissions/issue-336-repro.yml
Labels: bugfix

#340 fix: handle context accesses following calls
  src/audit/template_injection.rs
  src/expr/expr.pest
  src/expr/mod.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__template_injection-6.snap
  tests/test-data/template-injection/issue-339-repro.yml
Labels: bugfix

#344 docs: more trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#343 fix: setup-go's cache-control is OptOut
  src/audit/cache_poisoning.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__cache_poisoning-11.snap
  tests/test-data/cache-poisoning/issue-343-repro.yml
Labels: bugfix

#346 feat: augments the list of cache-aware action in cache-audit
  src/audit/cache_poisoning.rs
Labels: enhancement

#347 refactor: cache control types
  src/audit/cache_poisoning.rs
Labels: refactor

#351 docs: update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#354 feat: github-env: use tree-sitter queries
  Cargo.lock
  Cargo.toml
  src/audit/github_env.rs
Labels: enhancement

#331 feat: composite action support
  Cargo.lock
  Cargo.toml
  docs/audits.md
  docs/configuration.md
  docs/quickstart.md
  docs/snippets/help.txt
  docs/usage.md
  src/audit/artipacked.rs
  src/audit/cache_poisoning.rs
  src/audit/dangerous_triggers.rs
  src/audit/excessive_permissions.rs
  src/audit/github_env.rs
  src/audit/hardcoded_container_credentials.rs
  src/audit/impostor_commit.rs
  src/audit/insecure_commands.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/mod.rs
  src/audit/ref_confusion.rs
  src/audit/self_hosted_runner.rs
  src/audit/template_injection.rs
  src/audit/unpinned_uses.rs
  src/audit/use_trusted_publishing.rs
  src/finding/locate.rs
  src/finding/mod.rs
  src/github_api.rs
  src/main.rs
  src/models.rs
  src/registry.rs
  src/render.rs
  src/sarif.rs
  src/utils.rs
Labels: enhancement

#357 docs: add limitations section
  docs/limitations.md
  mkdocs.yml
Labels: documentation

#358 feat: github-env: support composite actions
  src/audit/github_env.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__github_env.snap
  tests/test-data/github-env/action.yml
Labels: enhancement

#359 feat: insecure-commands: support composite actions
  docs/audits.md
  src/audit/insecure_commands.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__insecure_commands-3.snap
  tests/test-data/insecure-commands/action.yml
Labels: enhancement

#361 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#368 deps: bump yamlpath
  Cargo.lock
  Cargo.toml
Labels: bugfix

#369 docs: installation: add badges
  docs/installation.md
Labels: documentation, chore

#370 docs: update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#371 feat: add argument --ghe-hostname for GHE Servers
  docs/snippets/help.txt
  docs/usage.md
  src/audit/github_env.rs
  src/github_api.rs
  src/main.rs
  src/state.rs
Labels: enhancement
