Repository zizmorcore/zizmor, pull requests merged in 2024-11, with the labels that each got.

#98 docs: add an example GHA workflow
  .github/workflows/zizmor.yml
  docs/usage.md
  mkdocs.yml
Labels: documentation

#100 docs: update readme
  README.md
Labels: documentation

#99 docs: show example for usage in private repos
  docs/usage.md
Labels: documentation

#101 chore: prep 0.1.5
  Cargo.lock
  Cargo.toml
Labels: chore

#103 docs: explains execution requirements for all available audits
  docs/audits.md
  mkdocs.yml
Labels: documentation

#104 feat: accept multiple arguments as inputs
  src/main.rs
Labels: enhancement, cli

#105 feat: pre-commit hook for other repos to use
  .pre-commit-hooks.yaml
  docs/usage.md
Labels: documentation, enhancement, packaging

#107 chore: fix some usage links
  docs/usage.md
Labels: chore

#108 chore: prep 0.1.6
  Cargo.lock
  Cargo.toml
Labels: chore

#110 chore: add issue forms + config
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: chore

#111 chore: add description to `--help`
  src/main.rs
Labels: cli

#112 fix: bump github-actions-models
  Cargo.lock
  Cargo.toml
Labels: bugfix

#115 docs: link directly to bug-report template
  README.md
  docs/index.md
Labels: documentation

#120 fix: bump github-actions-models
  Cargo.lock
  Cargo.toml
Labels: bugfix

#116 feat: configuration file support
  docs/configuration.md
  docs/usage.md
  mkdocs.yml
  src/audit/artipacked.rs
  src/audit/impostor_commit.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/ref_confusion.rs
  src/audit/self_hosted_runner.rs
  src/config.rs
  src/main.rs
  src/render.rs
  src/state.rs
Labels: cli, config

#123 chore: prep 0.2.0
  Cargo.lock
  Cargo.toml
Labels: chore

#126 refactor: clean up expr APIs slightly
  Cargo.lock
  Cargo.toml
  src/expr/mod.rs
Labels: refactor

#131 fix: bump github-actions-models
  Cargo.lock
  Cargo.toml
Labels: bugfix

#127 feat: analyze expressions for safety
  src/audit/template_injection.rs
  src/expr/expr.pest
  src/expr/mod.rs
  src/finding/mod.rs
Labels: enhancement

#132 chore: prep 0.2.1
  Cargo.lock
  Cargo.toml
Labels: chore

#133 feat: exit code support
  docs/usage.md
  src/finding/mod.rs
  src/main.rs
  src/registry.rs
  src/render.rs
  src/sarif.rs
  tests/acceptance.rs
Labels: enhancement, cli

#137 fix: github.event.merge_group.base_sha is a safe context
  src/audit/template_injection.rs
Labels: false-positive, bugfix

#136 fix: exclude information about the repo and owner
  src/audit/template_injection.rs
Labels: false-positive, bugfix

#140 fix: use the correct link for the self-hosted example file.
  docs/audits.md
Labels: documentation

#142 feat: add `--no-config`
  src/config.rs
  src/main.rs
Labels: enhancement, cli

#143 docs: misc improvements
  .github/workflows/ci.yml
  Makefile
  docs/configuration.md
  docs/development.md
  docs/quickstart.md
  docs/snippets/help.txt
  docs/usage.md
  mkdocs.yml
Labels: documentation

#144 chore: prep 0.3.0
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
Labels: chore

#145 fix(docs): fix repo links
  docs/audits.md
Labels: documentation

#146 feat(docs): add palette changer, icon, favicon
  docs/assets/favicon48x48.png
  docs/assets/rainbow.svg
  mkdocs.yml
Labels: documentation

#150 docs: update version in pre-commit hook
  docs/usage.md
Labels: documentation

#155 docs: fix quickstart grammar
  docs/quickstart.md
Labels: documentation

#157 fix(cli): remove '0 ignored' from another place
  src/render.rs
Labels: cli, bugfix

#158 perf: speed up impostor-commit's fast path
  src/audit/impostor_commit.rs
  src/github_api.rs
Labels: performance

#159 fix(cli): fixup error printing
  src/main.rs
  src/registry.rs
Labels: cli, bugfix

#160 chore: prep 0.3.2
  Cargo.lock
  Cargo.toml
Labels: chore

#163 Only deploy to GitHub Pages for upstream
  .github/workflows/site.yml
Labels: no-changelog, chore

#161 feat: unpinned-uses audit
  docs/audits.md
  mkdocs.yml
  src/audit/impostor_commit.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/mod.rs
  src/audit/ref_confusion.rs
  src/audit/unpinned_uses.rs
  src/main.rs
  src/models.rs
  tests/acceptance.rs
  tests/test-data/unpinned-uses.yml
Labels: enhancement, new-audit

#165 chore: add release categories
  .github/release.yml
Labels: chore

#166 chore: prep 0.4.0
  Cargo.lock
  Cargo.toml
Labels: chore

#167 docs: rewrite audit docs
  docs/audits.md
  mkdocs.yml
Labels: documentation

#172 feat: improve workflow registry error
  src/main.rs
Labels: enhancement

#176 feat: unsecure-commands-allowed audit
  .gitignore
  docs/audits.md
  src/audit/insecure_commands.rs
  src/audit/mod.rs
  src/main.rs
  tests/acceptance.rs
  tests/test-data/insecure-commands.yml
Labels: enhancement, new-audit

#180 docs: more badges
  README.md
  docs/index.md
  docs/installation.md
Labels: documentation

#182 docs: adds recommentations on how to add or change audits
  docs/audits.md
  docs/development.md
Labels: documentation

#183 chore: prep 0.5.0
  Cargo.lock
  Cargo.toml
Labels: chore

#185 refactor: simplify use of WorkflowAudit trait
  docs/development.md
  src/audit/known_vulnerable_actions.rs
  src/audit/mod.rs
  src/audit/template_injection.rs
  src/audit/unpinned_uses.rs
  src/audit/use_trusted_publishing.rs
  src/models.rs
Labels: refactor

#188 refactor: add Audit supertrait
  docs/development.md
  src/audit/artipacked.rs
  src/audit/dangerous_triggers.rs
  src/audit/excessive_permissions.rs
  src/audit/hardcoded_container_credentials.rs
  src/audit/impostor_commit.rs
  src/audit/insecure_commands.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/mod.rs
  src/audit/ref_confusion.rs
  src/audit/self_hosted_runner.rs
  src/audit/template_injection.rs
  src/audit/unpinned_uses.rs
  src/audit/use_trusted_publishing.rs
  src/finding/mod.rs
  src/main.rs
  src/render.rs
Labels: refactor

#187 feat: adds support to inlined ignores
  src/finding/mod.rs
  src/models.rs
  src/registry.rs
  tests/acceptance.rs
  tests/test-data/inlined-ignores.yml
Labels: enhancement

#190 docs: document ignore comments
  docs/usage.md
Labels: documentation

#193 feat: add `--min-severity`
  docs/snippets/help.txt
  docs/usage.md
  src/finding/mod.rs
  src/main.rs
  src/registry.rs
Labels: enhancement, cli

#194 docs: add page descriptions
  docs/audits.md
  docs/configuration.md
  docs/development.md
  docs/installation.md
  docs/usage.md
  mkdocs.yml
Labels: documentation

#192 feat: adds new github-env audit
  docs/audits.md
  src/audit/dangerous_triggers.rs
  src/audit/github_env.rs
  src/audit/mod.rs
  src/main.rs
  src/models.rs
  tests/acceptance.rs
  tests/test-data/github_env.yml
Labels: enhancement, new-audit

#198 docs: add more useful 3p references
  docs/audits.md
Labels: documentation

#199 feat: improve precision for github-env
  Cargo.lock
  Cargo.toml
  src/audit/github_env.rs
Labels: enhancement

#203 chore: add FUNDING.yml
  .github/FUNDING.yml
Labels: chore

#200 feat: generalized ignore comments
  Cargo.lock
  Cargo.toml
  docs/usage.md
  src/finding/locate.rs
  src/finding/mod.rs
Labels: enhancement

#206 chore: prep 0.6.0
  Cargo.lock
  Cargo.toml
Labels: chore

#207 chore: tweak zizmor's self-description
  Cargo.toml
  README.md
  docs/index.md
  docs/snippets/help.txt
Labels: chore

#211 fix: bump github-actions-models
  Cargo.lock
  Cargo.toml
Labels: bugfix

#212 chore: `cargo update`
  Cargo.lock
Labels: dependencies

#214 chore: bump github_actions_models, change usage
  Cargo.lock
  Cargo.toml
  src/audit/self_hosted_runner.rs
Labels: chore, dependencies

#205 Split unpinned-uses into two separate checks
  docs/audits.md
  src/audit/unpinned_uses.rs
  src/models.rs
  tests/acceptance.rs
  tests/test-data/artipacked.yml
  tests/test-data/inlined-ignores.yml
  tests/test-data/template-injection.yml
  tests/test-data/use-trusted-publishing.yml
Labels: enhancement

#208 feat: even more precision for bash steps in github-env
  Cargo.lock
  Cargo.toml
  src/audit/github_env.rs
Labels: enhancement

#213 feat: add Step::default_shell
  src/audit/github_env.rs
  src/models.rs
Labels: enhancement

#216 feat: handle `shell: sh` in github-env
  src/audit/github_env.rs
Labels: enhancement

#217 feat: primitive Windows batch handling in github-env
  src/audit/github_env.rs
Labels: enhancement

#219 feat: unpinned-uses: make unhashed check pedantic for now
  docs/audits.md
  src/audit/unpinned_uses.rs
Labels: enhancement
