Repository zizmorcore/zizmor, pull requests merged in 2025-06, with the labels that each got.

#887 fix: remove spurious panic in env handling
  .github/workflows/zizmor.yml
  Cargo.lock
  Cargo.toml
  crates/github-actions-models/Cargo.toml
  crates/github-actions-models/src/action.rs
  crates/github-actions-models/src/workflow/job.rs
  crates/github-actions-models/tests/test_workflow.rs
  crates/zizmor/src/audit/insecure_commands.rs
  crates/zizmor/src/models.rs
  crates/zizmor/src/models/coordinate.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-13.snap
  crates/zizmor/tests/integration/test-data/template-injection/issue-883-repro/action.yml
  docs/release-notes.md
Labels: bugfix

#892 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#888 refactor: add RewriteFragment for format-preserving YAML string edits
  crates/github-actions-models/src/action.rs
  crates/yamlpath/src/lib.rs
  crates/yamlpath/tests/integration_test.rs
  crates/yamlpath/tests/testcases/exact-features.yml
  crates/yamlpath/tests/testcases/flow.yml
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/src/yaml_patch/mod.rs
Labels: enhancement, refactor

#895 docs: mention zizmorcore/zizmor-action
  docs/assets/chips.css
  docs/usage.md
  mkdocs.yml
Labels: documentation, enhancement

#896 feat: artipacked now supported composite actions
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/cache_poisoning.rs
  crates/zizmor/src/audit/dangerous_triggers.rs
  crates/zizmor/src/audit/forbidden_uses.rs
  crates/zizmor/src/audit/known_vulnerable_actions.rs
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/audit/obfuscation.rs
  crates/zizmor/src/audit/overprovisioned_secrets.rs
  crates/zizmor/src/audit/stale_action_refs.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/unpinned_uses.rs
  crates/zizmor/src/audit/unredacted_secrets.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/src/models.rs
  crates/zizmor/src/models/coordinate.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-5.snap
  crates/zizmor/tests/integration/test-data/artipacked/demo-action/action.yml
  docs/release-notes.md
Labels: enhancement

#897 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#898 chore: add zizmor's crate to the security category
  crates/zizmor/Cargo.toml
Labels: chore

#899 feat: support composite actions in use-trusted-publishing
  crates/zizmor/src/audit/use_trusted_publishing.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__use_trusted_publishing-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__use_trusted_publishing.snap
  crates/zizmor/tests/integration/test-data/use-trusted-publishing/demo-action/action.yml
  docs/release-notes.md
Labels: enhancement

#905 feat: improve bot-conditions checks
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/models.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__bot_conditions.snap
  crates/zizmor/tests/integration/test-data/bot-conditions.yml
  docs/release-notes.md
Labels: enhancement

#908 chore(docs): tweak chip rendering
  docs/assets/chips.css
  docs/usage.md
Labels: documentation, chore

#910 chore(tests): add more flow test cases
  crates/yamlpath/tests/testcases/flow.yml
Labels: tests, chore

#916 bugfix: put longer comp_op variants ahead
  crates/github-actions-expressions/src/expr.pest
  crates/github-actions-expressions/src/lib.rs
  docs/release-notes.md
Labels: bugfix

#917 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#911 feat: handle default envvars when fixing template injections
  crates/github-actions-expressions/src/context.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/models.rs
  crates/zizmor/src/models/coordinate.rs
  crates/zizmor/src/utils.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-5.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-7.snap
  docs/release-notes.md
Labels: enhancement

#919 feat: model input capabilities in workflows and actions
  crates/github-actions-expressions/src/context.rs
  crates/github-actions-models/src/workflow/event.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/models.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/src/models/coordinate.rs
  crates/zizmor/src/models/inputs.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/src/utils.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-13.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-8.snap
  crates/zizmor/tests/integration/test-data/template-injection/input-caps.yml
Labels: enhancement

#922 chore(docs): release notes for #919
  docs/release-notes.md
Labels: documentation, chore

#926 chore: fix refresh-schemas target
  Makefile
  crates/zizmor/src/data/github-action.json
  crates/zizmor/src/data/github-workflow.json
Labels: chore

#934 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#904 Handle flow and block style values properly
  .gitignore
  Cargo.lock
  crates/yamlpath/Cargo.toml
  crates/yamlpath/src/lib.rs
  crates/yamlpath/tests/testcases/exact-features.yml
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/src/yaml_patch/mod.rs
Labels: enhancement, bugfix

#941 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#940 chore: remove a root level special case
  Cargo.lock
  Cargo.toml
  crates/yamlpath/Cargo.toml
  crates/yamlpath/src/lib.rs
  crates/zizmor/src/yaml_patch/mod.rs
Labels: tests, chore, refactor

#942 chore(tests): rename tests for consistency
  crates/zizmor/src/yaml_patch/mod.rs
Labels: tests, chore

#937 feat: new audit: anonymous-definition
  crates/zizmor/src/audit/anonymous_definition.rs
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/main.rs
  crates/zizmor/tests/integration/acceptance.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_569.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_726.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__anonymous_definition-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__anonymous_definition.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__ref_confusion.snap
  crates/zizmor/tests/integration/test-data/anonymous-definition.yml
  docs/audits.md
  docs/release-notes.md
Labels: enhancement

#944 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#945 refactor: add spanning to expressions
  crates/github-actions-expressions/src/context.rs
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/overprovisioned_secrets.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/unredacted_secrets.rs
  crates/zizmor/src/audit/unsound_contains.rs
  crates/zizmor/src/utils.rs
Labels: refactor

#948 docs: Unfix accidentally-fixed pinning example
  docs/usage.md
Labels: documentation

#951 chore(cli): add --thanks
  README.md
  crates/zizmor/src/main.rs
  docs/snippets/help.txt
  docs/snippets/sponsors.html
  docs/snippets/sponsors.json
Labels: cli, chore

#955 chore: add a debug message when registering inputs
  crates/zizmor/src/registry.rs
Labels: chore

#956 feat: better error messages for invalid inputs
  Cargo.lock
  crates/github-actions-models/Cargo.toml
  crates/github-actions-models/src/common.rs
  crates/github-actions-models/src/workflow/job.rs
  crates/zizmor/src/main.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/src/utils.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-10.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-2.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-3.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-4.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-5.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-6.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-7.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-8.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-9.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__menagerie-2.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__menagerie.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-10.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-11.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-12.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-6.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-7.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-8.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-9.snap
  docs/release-notes.md
Labels: enhancement

#960 bugfix: eliminate a panic when auditing composite actions
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/main.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/tests/integration/e2e.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__pr_960_backstop.snap
  crates/zizmor/tests/integration/test-data/pr-960-backstop/action.yml
Labels: bugfix

#961 chore(docs): add Trail of Bits as a sponsor
  README.md
  docs/snippets/sponsors.html
  docs/snippets/sponsors.json
Labels: documentation, chore

#958 template-injection: add subfeatures
  crates/github-actions-expressions/src/context.rs
  crates/github-actions-expressions/src/expr.pest
  crates/github-actions-expressions/src/lib.rs
  crates/yamlpath/src/lib.rs
  crates/yamlpath/tests/integration_test.rs
  crates/yamlpath/tests/testcases/flow.yml
  crates/yamlpath/tests/testcases/key-only-features.yml
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/overprovisioned_secrets.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/unsound_contains.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__bot_conditions.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__github_output.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-11.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-12.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-13.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-14.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-4.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-5.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-6.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-8.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection.snap
  crates/zizmor/tests/integration/test-data/template-injection/multiline-expression.yml
  docs/release-notes.md
Labels: enhancement

#966 chore: refactor fix input key handling
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/finding.rs
  crates/zizmor/src/fix.rs
  crates/zizmor/src/registry.rs
Labels: refactor

#969 feat: detect computed indices as potential obfuscation
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/src/audit/obfuscation.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/unsound_contains.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_569.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__obfuscation-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__obfuscation.snap
  crates/zizmor/tests/integration/test-data/obfuscation/computed-indices.yml
  docs/release-notes.md
Labels: refactor

#970 chore(deps): bump all support crate versions
  Cargo.lock
  Cargo.toml
  crates/github-actions-expressions/Cargo.toml
  crates/github-actions-models/Cargo.toml
  crates/yamlpath/Cargo.toml
Labels: chore, dependencies

#974 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#975 refactor: prepare fix mode for a public experimental release
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/finding.rs
  crates/zizmor/src/main.rs
  crates/zizmor/src/output/fix.rs
  crates/zizmor/src/output/plain.rs
  crates/zizmor/src/registry.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-3.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-4.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-5.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-4.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-5.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-8.snap
  docs/assets/chips.css
  docs/snippets/help.txt
  docs/usage.md
Labels: refactor

#976 chore(deps): bump yamlpath
  Cargo.lock
  Cargo.toml
  crates/yamlpath/Cargo.toml
Labels: chore, dependencies

#977 chore: prep for release v1.10.0
  Cargo.lock
  crates/zizmor/Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#980 chore(deps): bump http-cache-reqwest to 0.15.2
  Cargo.lock
  Cargo.toml
  crates/zizmor/src/github_api.rs
Labels: chore, dependencies

#982 chore(deps): bump http-cache-reqwest to 0.16.0
  Cargo.lock
  Cargo.toml
Labels: chore, dependencies

#921 Add Fix for bot-conditions audit rule
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__bot_conditions.snap
  docs/release-notes.md
Labels: enhancement, autofix

#989 bugfix: repro, #988
  Cargo.lock
  Cargo.toml
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/Cargo.toml
  crates/zizmor/src/finding/location.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-15.snap
  crates/zizmor/tests/integration/test-data/template-injection/issue-988-repro.yml
  docs/release-notes.md
Labels: bugfix
