Repository zizmorcore/zizmor, pull requests merged in 2025-07, with the labels that each got.

#1004 chore(ci): add environments to crates.io workflows
  .github/workflows/release-support-crate.yml
  .github/workflows/release-zizmor-crate.yml
Labels: chore, ci/cd

#1005 chore(ci): refactor package name handling for support crates
  .github/workflows/release-support-crate.yml
  Cargo.lock
  Cargo.toml
  crates/yamlpath/Cargo.toml
Labels: chore, ci/cd

#1006 chore(ci): try using TP for support crates
  .github/workflows/release-support-crate.yml
  Cargo.lock
  Cargo.toml
  crates/github-actions-expressions/Cargo.toml
Labels: chore, ci/cd

#1007 chore(ci): move zizmor crate publish to trusted publishing
  .github/workflows/release-zizmor-crate.yml
Labels: chore, ci/cd

#1008 chore: prep for 1.11.1-rc1 release
  Cargo.lock
  crates/zizmor/Cargo.toml
Labels: chore, ci/cd

#1001 Extract yamlpatch into a support crate
  .github/workflows/release-support-crate.yml
  Cargo.lock
  Cargo.toml
  crates/yamlpatch/Cargo.toml
  crates/yamlpatch/LICENSE
  crates/yamlpatch/README.md
  crates/yamlpatch/src/lib.rs
  crates/yamlpatch/tests/unit_tests.rs
  crates/zizmor/Cargo.toml
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/finding.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/src/main.rs
  crates/zizmor/src/yaml_patch/mod.rs
Labels: refactor

#1013 bugfix(cli): forbid some empty values for options
  crates/zizmor/src/main.rs
  crates/zizmor/src/state.rs
Labels: cli, bugfix

#1014 refactor: dedupe route/query types
  crates/yamlpatch/src/lib.rs
  crates/yamlpatch/tests/unit_tests.rs
  crates/yamlpath/Cargo.toml
  crates/yamlpath/src/lib.rs
  crates/yamlpath/tests/integration_test.rs
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/cache_poisoning.rs
  crates/zizmor/src/audit/dangerous_triggers.rs
  crates/zizmor/src/audit/excessive_permissions.rs
  crates/zizmor/src/audit/forbidden_uses.rs
  crates/zizmor/src/audit/github_env.rs
  crates/zizmor/src/audit/hardcoded_container_credentials.rs
  crates/zizmor/src/audit/insecure_commands.rs
  crates/zizmor/src/audit/known_vulnerable_actions.rs
  crates/zizmor/src/audit/obfuscation.rs
  crates/zizmor/src/audit/ref_confusion.rs
  crates/zizmor/src/audit/secrets_inherit.rs
  crates/zizmor/src/audit/self_hosted_runner.rs
  crates/zizmor/src/audit/stale_action_refs.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/unpinned_images.rs
  crates/zizmor/src/audit/unpinned_uses.rs
  crates/zizmor/src/audit/unsound_contains.rs
  crates/zizmor/src/audit/use_trusted_publishing.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__anonymous_definition.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__excessive_permissions-3.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-5.snap
Labels: refactor

#1015 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#1016 chore: bump yamlpatch, yamlpath crates
  Cargo.lock
  Cargo.toml
  crates/yamlpatch/Cargo.toml
  crates/yamlpath/Cargo.toml
Labels: chore

#1025 chore(docs): update sponsors
  README.md
  docs/snippets/render-sponsors.py
  docs/snippets/sponsors.html
  docs/snippets/sponsors.json
Labels: documentation, chore

#1027 bugfix: sanitize gh_token & avoid panic
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/cache_poisoning.rs
  crates/zizmor/src/audit/github_env.rs
  crates/zizmor/src/audit/impostor_commit.rs
  crates/zizmor/src/audit/known_vulnerable_actions.rs
  crates/zizmor/src/audit/ref_confusion.rs
  crates/zizmor/src/audit/stale_action_refs.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/github_api.rs
  crates/zizmor/src/lsp.rs
  crates/zizmor/src/main.rs
  crates/zizmor/src/state.rs
  docs/release-notes.md
Labels: cli, bugfix

#1031 chore: remove unused imports in tests
  crates/zizmor/src/finding/location.rs
Labels: tests, chore

#1032 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#1037 refactor: generalize use-trusted-publishing audit
  crates/zizmor/src/audit/cache_poisoning.rs
  crates/zizmor/src/audit/use_trusted_publishing.rs
  crates/zizmor/src/models/coordinate.rs
  crates/zizmor/src/utils.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-4.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__use_trusted_publishing.snap
  crates/zizmor/tests/integration/test-data/use-trusted-publishing.yml
Labels: refactor

#1038 feat: CLI benchmarking harness
  .github/workflows/benchmark-base.yml
  .github/workflows/benchmark-pr-1p.yml
  Makefile
  bench/.gitignore
  bench/benchmark.py
  bench/benchmarks.json
Labels: performance, benchmarking

#1040 ci: add some TODOs
  .github/workflows/benchmark-base.yml
  .github/workflows/benchmark-pr-1p.yml
Labels: chore, ci/cd

#1041 refactor: remove RwLock from github-env audit
  crates/zizmor/src/audit/github_env.rs
Labels: refactor

#1042 feat: support crates.io in use-trusted-publishing
  .github/workflows/release-binaries.yml
  .github/workflows/release-docker.yml
  crates/zizmor/src/audit/github_env.rs
  crates/zizmor/src/audit/use_trusted_publishing.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/src/utils.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-12.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-13.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-4.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-6.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-7.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-8.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__use_trusted_publishing-3.snap
  crates/zizmor/tests/integration/test-data/cache-poisoning.yml
  crates/zizmor/tests/integration/test-data/cache-poisoning/caching-enabled-by-default.yml
  crates/zizmor/tests/integration/test-data/cache-poisoning/caching-not-configurable.yml
  crates/zizmor/tests/integration/test-data/cache-poisoning/caching-opt-in-expression.yml
  crates/zizmor/tests/integration/test-data/cache-poisoning/caching-opt-out.yml
  crates/zizmor/tests/integration/test-data/cache-poisoning/no-cache-aware-steps.yml
  crates/zizmor/tests/integration/test-data/cache-poisoning/workflow-release-branch-trigger.yml
  crates/zizmor/tests/integration/test-data/cache-poisoning/workflow-tag-trigger.yml
  crates/zizmor/tests/integration/test-data/use-trusted-publishing/cargo-publish.yml
  docs/audits.md
  docs/release-notes.md
Labels: enhancement

#1046 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#1047 chore(docs): bump trophies, update links
  docs/audits.md
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#1050 chore(docs): improve the dev docs a bit
  docs/development.md
Labels: documentation, chore

#1051 chore(ci): disable benchmarking for PRs with 'no-benchmark' label
  .github/workflows/benchmark-pr-1p.yml
Labels: chore, ci/cd, no-benchmark
