Repository zizmorcore/zizmor, pull requests merged in 2025-04, with the labels that each got.

#641 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#640 feat: basic dataflow for context expansion
  docs/release-notes.md
  src/audit/overprovisioned_secrets.rs
  src/audit/template_injection.rs
  src/audit/unredacted_secrets.rs
  src/expr/mod.rs
  tests/integration/snapshots/integration__snapshot__template_injection-6.snap
  tests/integration/test-data/template-injection/dataflow.yml
Labels: enhancement

#644 bugfix: cache-poisoning: fix false positive for docker/setup-buildx-action
  docs/release-notes.md
  src/audit/cache_poisoning.rs
  src/models.rs
  src/models/coordinate.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__snapshot__cache_poisoning-15.snap
  tests/integration/test-data/cache-poisoning/issue-378-repro.yml
  tests/integration/test-data/cache-poisoning/issue-642-repro.yml
Labels: enhancement, bugfix

#649 bugfix: bump github-actions-models to 0.27.0
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
Labels: bugfix

#653 bugfix: bump github-actions-models to 0.28.0
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
Labels: bugfix, dependencies

#655 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#656 usage: note when `--format=github` is available
  docs/usage.md
Labels: documentation, chore

#657 feat: add JSON format versioning
  docs/release-notes.md
  docs/snippets/help.txt
  docs/usage.md
  src/main.rs
Labels: enhancement, cli

#660 bugfix: bump yamlpath, fix #659
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__snapshot__unpinned_uses-5.snap
  tests/integration/test-data/unpinned-uses/issue-659-repro.yml
Labels: bugfix

#661 bugfix: github.job is not a template injection risk
  docs/release-notes.md
  src/audit/template_injection.rs
Labels: bugfix

#667 ci: convert Dockerfile to Wolfi
  Dockerfile
Labels: enhancement

#668 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#664 feat: new audit: forbidden-uses
  docs/audits.md
  src/audit/forbidden_uses.rs
  src/audit/mod.rs
  src/audit/unpinned_uses.rs
  src/main.rs
  src/models/uses.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  tests/integration/snapshots/integration__e2e__issue_569.snap
  tests/integration/snapshots/integration__e2e__menagerie-2.snap
  tests/integration/snapshots/integration__e2e__menagerie.snap
  tests/integration/snapshots/integration__snapshot__forbidden_uses-2.snap
  tests/integration/snapshots/integration__snapshot__forbidden_uses-3.snap
  tests/integration/snapshots/integration__snapshot__forbidden_uses-4.snap
  tests/integration/snapshots/integration__snapshot__forbidden_uses.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-10.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-7.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-8.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-9.snap
  tests/integration/test-data/forbidden-uses/configs/allow-all.yml
  tests/integration/test-data/forbidden-uses/configs/allow-some.yml
  tests/integration/test-data/forbidden-uses/configs/deny-all.yml
  tests/integration/test-data/forbidden-uses/configs/deny-some.yml
  tests/integration/test-data/forbidden-uses/forbidden-uses-menagerie.yml
Labels: new-audit

#671 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#675 bugfix: template-injection: mark another context as safe
  docs/release-notes.md
  src/audit/template_injection.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__snapshot__template_injection-9.snap
  tests/integration/test-data/template-injection/false-positive-menagerie.yml
Labels: false-positive, bugfix

#670 feat: generalize RepositoryUsesPattern
  docs/audits.md
  src/audit/unpinned_uses.rs
  src/models/uses.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__snapshot__unpinned-uses-composite-config-2.snap
  tests/integration/snapshots/integration__snapshot__unpinned-uses-composite-config.snap
  tests/integration/snapshots/integration__snapshot__unpinned-uses-empty-config.snap
  tests/integration/snapshots/integration__snapshot__unpinned-uses-hash-pin-everything-config.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-10.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-7.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-8.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-9.snap
  tests/integration/test-data/unpinned-uses/configs/composite-2.yml
  tests/integration/test-data/unpinned-uses/menagerie-of-uses.yml
Labels: enhancement

#679 chore: bump github-actions-models to 0.28.1
  Cargo.lock
  Cargo.toml
  src/models/uses.rs
Labels: chore, dependencies

#681 chore: prep for release 1.6.0
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#682 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#687 chore(docs): clarify default rule in explicit config
  docs/audits.md
Labels: documentation, chore

#688 docs: recommend GitHubSecurityLab/actions-permissions
  docs/audits.md
Labels: documentation

#683 feat: new audit: obfuscation
  docs/audits.md
  docs/release-notes.md
  src/audit/mod.rs
  src/audit/obfuscation.rs
  src/audit/overprovisioned_secrets.rs
  src/audit/unredacted_secrets.rs
  src/expr/mod.rs
  src/main.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__e2e__issue_569.snap
  tests/integration/snapshots/integration__snapshot__obfuscation.snap
  tests/integration/test-data/obfuscation.yml
Labels: enhancement, new-audit

#693 feat: github_api: improve 403 errors slightly
  src/github_api.rs
Labels: enhancement

#694 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#698 tests: check zizmor exit code
  tests/integration/common.rs
  tests/integration/e2e.rs
  tests/integration/snapshot.rs
Labels: tests

#699 chore(docs): update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#700 chore(docs): update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#697 feat: reduce code duplication for workflow step handling
  src/audit/artipacked.rs
  src/audit/bot_conditions.rs
  src/audit/forbidden_uses.rs
  src/audit/github_env.rs
  src/audit/impostor_commit.rs
  src/audit/insecure_commands.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/obfuscation.rs
  src/audit/ref_confusion.rs
  src/audit/template_injection.rs
  src/audit/unpinned_uses.rs
  src/audit/use_trusted_publishing.rs
  src/models.rs
  src/models/coordinate.rs
Labels: refactor

#705 chore(docs): hash-pin setup-uv in usage.md
  docs/usage.md
Labels: documentation, chore

#706 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#703 feat: further reduce step handling code duplication
  src/audit/artipacked.rs
  src/audit/bot_conditions.rs
  src/audit/cache_poisoning.rs
  src/audit/dangerous_triggers.rs
  src/audit/excessive_permissions.rs
  src/audit/forbidden_uses.rs
  src/audit/github_env.rs
  src/audit/hardcoded_container_credentials.rs
  src/audit/impostor_commit.rs
  src/audit/insecure_commands.rs
  src/audit/known_vulnerable_actions.rs
  src/audit/mod.rs
  src/audit/obfuscation.rs
  src/audit/overprovisioned_secrets.rs
  src/audit/ref_confusion.rs
  src/audit/secrets_inherit.rs
  src/audit/self_hosted_runner.rs
  src/audit/template_injection.rs
  src/audit/unpinned_uses.rs
  src/audit/unredacted_secrets.rs
  src/audit/use_trusted_publishing.rs
  src/finding/mod.rs
  src/models.rs
  src/models/coordinate.rs
  src/output/plain.rs
  src/utils.rs
Labels: enhancement, refactor

#707 chore: models: remove pub(crate) from some fields
  src/models.rs
Labels: chore

#708 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#710 bugfix: sarif: prefix ID, add rule names
  docs/release-notes.md
  src/output/sarif.rs
Labels: bugfix, test-sarif-presentation

#717 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#720 chore(ci): add refresh-schemas workflow
  .github/workflows/refresh-schemas.yml
Labels: chore, ci/cd

#721 chore(ci): fix makefile target
  Makefile
Labels: chore, ci/cd

#727 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#729 chore: remove duplicate context
  src/audit/known_vulnerable_actions.rs
  src/github_api.rs
Labels: chore

#728 doc: mention insta `--force-update-snapshots`
  docs/development.md
Labels: documentation
