Repository zizmorcore/zizmor, pull requests merged in 2025-05, with the labels that each got.

#731 bugfix: fix edge case in remote audit input collection
  docs/release-notes.md
  src/github_api.rs
  tests/integration/e2e.rs
  tests/integration/snapshots/integration__e2e__issue_726.snap
Labels: bugfix

#577 New Audit `unsound-contains`: Checks for problematic `contains()` usage
  docs/audits.md
  docs/release-notes.md
  src/audit/mod.rs
  src/audit/unsound_contains.rs
  src/main.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__snapshot__unsound_contains.snap
  tests/integration/test-data/unsound-contains.yml
Labels: enhancement, new-audit

#733 feat: add unpinned-container-images check
  docs/audits.md
  docs/release-notes.md
  src/audit/mod.rs
  src/audit/unpinned_images.rs
  src/main.rs
  tests/integration/acceptance.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  tests/integration/snapshots/integration__snapshot__unpinned_images.snap
  tests/integration/test-data/inlined-ignores.yml
  tests/integration/test-data/unpinned-images.yml
Labels: enhancement, new-audit

#739 chore(docs): put examples in example blocks
  docs/audits.md
Labels: documentation, chore

#740 feat: emit pedantic finding for tagged OCI images
  docs/audits.md
  src/audit/unpinned_images.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__e2e__issue_569.snap
  tests/integration/snapshots/integration__snapshot__unpinned_images.snap
Labels: enhancement

#744 chore: remove old TODO comment
  src/audit/obfuscation.rs
Labels: chore

#748 feat: handle reducible index subexpressions
  src/audit/obfuscation.rs
  src/expr/mod.rs
  tests/integration/snapshots/integration__e2e__issue_569.snap
  tests/integration/snapshots/integration__snapshot__obfuscation.snap
  tests/integration/test-data/obfuscation.yml
Labels: enhancement, refactor

#750 feat: extend RepositoryUsesPattern to allow exact ref patterns
  docs/release-notes.md
  src/audit/unpinned_uses.rs
  src/models/uses.rs
  tests/integration/snapshot.rs
  tests/integration/snapshots/integration__snapshot__forbidden_uses-5.snap
  tests/integration/snapshots/integration__snapshot__forbidden_uses-6.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-12.snap
  tests/integration/test-data/forbidden-uses/configs/allow-some-refs.yml
  tests/integration/test-data/forbidden-uses/configs/deny-some-refs.yml
  tests/integration/test-data/unpinned-uses/configs/invalid-policy-syntax-6.yml
Labels: enhancement

#751 chore(docs): document repository patterns better
  docs/audits.md
  docs/configuration.md
Labels: documentation, chore

#752 refactor: remove old repo matching APIs
  src/audit/cache_poisoning.rs
  src/models/coordinate.rs
  src/models/uses.rs
Labels: refactor

#757 chore(docs): add Discord badge to README and docs
  README.md
  docs/index.md
Labels: documentation, chore

#759 chore(docs): mention @zizmorcore plans
  docs/release-notes.md
Labels: documentation, chore

#760 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#761 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#763 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#765 feat: tab completion
  Cargo.lock
  Cargo.toml
  docs/snippets/help.txt
  docs/usage.md
  src/main.rs
Labels: enhancement

#767 chore(docs): update release notes
  docs/release-notes.md
Labels: documentation, chore

#768 chore: prep for v1.7.0 release
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#769 chore: switch to docs.zizmor.sh
  CONTRIBUTING.md
  Cargo.toml
  README.md
  docs/release-notes.md
  mkdocs.yml
  src/audit/mod.rs
  src/main.rs
  tests/integration/snapshots/integration__e2e__invalid_config_file.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-10.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-11.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-12.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-6.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-7.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-8.snap
  tests/integration/snapshots/integration__snapshot__unpinned_uses-9.snap
Labels: chore

#770 chore(docs): change URL
  docs/usage.md
Labels: documentation, chore

#771 chore(docs): more social links
  mkdocs.yml
Labels: documentation, chore

#775 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#776 chore(docs): the great @zizmorcore renaming
  CONTRIBUTING.md
  Cargo.toml
  README.md
  docs/development.md
  docs/index.md
  docs/installation.md
  docs/quickstart.md
  docs/release-notes.md
  docs/usage.md
  mkdocs.yml
  src/main.rs
  src/output/sarif.rs
  tests/integration/e2e.rs
  tests/integration/test-data/artipacked/issue-447-repro.yml
  tests/integration/test-data/cache-poisoning/issue-343-repro.yml
  tests/integration/test-data/cache-poisoning/issue-378-repro.yml
  tests/integration/test-data/cache-poisoning/issue-642-repro.yml
  tests/integration/test-data/excessive-permissions/issue-472-repro.yml
  tests/integration/test-data/template-injection/issue-22-repro.yml
  tests/integration/test-data/template-injection/issue-339-repro.yml
  tests/integration/test-data/template-injection/issue-418-repro.yml
  tests/integration/test-data/template-injection/pr-317-repro.yml
  tests/integration/test-data/unpinned-uses/issue-433-repro.yml
Labels: documentation, chore

#777 bugfix(ci): fix ZIZMOR_IMAGE for Docker builds
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/docker.yml
  .github/workflows/site.yml
  .github/workflows/test-output.yml
Labels: bugfix, ci/cd

#778 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#781 chore(docs): constrain permissions in workflow example
  .github/workflows/zizmor.yml
  docs/usage.md
Labels: documentation, chore

#782 chore(docs): bump trophies
  docs/snippets/trophies.txt
Labels: documentation, chore

#788 docs: add some hash-pinning tool recommendations
  docs/assets/magiclink.css
  docs/audits.md
  mkdocs.yml
Labels: documentation

#789 feat: add ZIZMOR_CONFIG
  docs/release-notes.md
  docs/snippets/help.txt
  docs/usage.md
  src/main.rs
Labels: enhancement, ci/cd

#790 chore(docs): add env to config precedence
  docs/configuration.md
Labels: documentation, chore

#791 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#793 build: fix paths in refresh-schemas target
  Makefile
Labels: chore

#796 chore: clean up issue forms
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: chore

#797 refactor: split expr parser into its own crate
  .github/workflows/docker.yml
  .github/workflows/pypi.yml
  .github/workflows/refresh-schemas.yml
  .github/workflows/release-crate.yml
  .github/workflows/release.yml
  .github/workflows/site.yml
  Cargo.lock
  Cargo.toml
  crates/github-actions-expressions/Cargo.toml
  crates/github-actions-expressions/src/expr.pest
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/Cargo.toml
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/github_env.rs
  crates/zizmor/src/audit/obfuscation.rs
  crates/zizmor/src/audit/overprovisioned_secrets.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/unredacted_secrets.rs
  crates/zizmor/src/audit/unsound_contains.rs
  crates/zizmor/src/main.rs
  docs/audits.md
Labels: refactor

#798 chore(ci): add notice to release-crate.yml
  .github/workflows/release-crate.yml
Labels: chore, ci/cd

#799 chore(docs): give github-actions-expressions a README
  Cargo.lock
  Cargo.toml
  crates/github-actions-expressions/Cargo.toml
  crates/github-actions-expressions/README.md
Labels: documentation, chore

#800 feat: add ContextPattern APIs
  crates/github-actions-expressions/src/context.rs
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/overprovisioned_secrets.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/unredacted_secrets.rs
  crates/zizmor/src/audit/unsound_contains.rs
Labels: enhancement

#804 chore(docs): more github-actions-expressions docs
  crates/github-actions-expressions/src/context.rs
  crates/github-actions-expressions/src/expr.pest
Labels: documentation, chore

#805 chore(deps): run `cargo autoinherit`
  Cargo.toml
  crates/zizmor/Cargo.toml
Labels: chore, dependencies

#806 test: add test for #749
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-10.snap
  crates/zizmor/tests/integration/test-data/template-injection/issue-749-repro.yml
  docs/release-notes.md
Labels: tests

#807 chore: enable missing_docs lint for github-actions-expressions
  Cargo.lock
  crates/github-actions-expressions/Cargo.toml
  crates/github-actions-expressions/src/lib.rs
Labels: documentation, chore

#809 chore(ci): bump actions, use zizmor-action
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .github/workflows/pypi.yml
  .github/workflows/release-crate.yml
  .github/workflows/release.yml
  .github/workflows/site.yml
  .github/workflows/test-output.yml
  .github/workflows/zizmor.yml
Labels: chore, ci/cd

#811 chore(ci): experiment with pinact
  .github/dependabot.yml
  .github/workflows/pinact.yml
  docs/audits.md
Labels: chore, ci/cd

#813 fix(ci): drop dry-run from pinact.yml
  .github/workflows/pinact.yml
Labels: bugfix, ci/cd

#815 chore(ci): undo pinact experiment
  .github/dependabot.yml
  .github/workflows/pinact.yml
Labels: chore, ci/cd

#817 chore: add pinact, apply pinact
  .github/pinact.yml
  .github/workflows/zizmor.yml
  Makefile
  docs/audits.md
  docs/usage.md
Labels: chore, ci/cd

#818 chore: limit pinact to docs, document usage
  .github/pinact.yml
  docs/development.md
Labels: documentation, chore

#820 chore(docs): use `json-v1` for JSON example
  docs/usage.md
Labels: documentation, chore

#821 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#824 chore(ci): unify release workflow names
  .github/workflows/release-docker.yml
  .github/workflows/release-pypi.yml
  .github/workflows/release-support-crate.yml
  .github/workflows/release-zizmor-crate.yml
Labels: chore, refactor, ci/cd

#825 refactor: bring yamlpath into repo
  .github/workflows/release-support-crate.yml
  Cargo.lock
  Cargo.toml
  crates/yamlpath/Cargo.toml
  crates/yamlpath/LICENSE
  crates/yamlpath/README.md
  crates/yamlpath/src/lib.rs
  crates/yamlpath/tests/integration_test.rs
  crates/yamlpath/tests/testcases/basic.yml
  crates/yamlpath/tests/testcases/comments.yml
  crates/yamlpath/tests/testcases/directives.yml
  crates/yamlpath/tests/testcases/flow.yml
  crates/yamlpath/tests/testcases/interceding-comment.yml
  crates/yamlpath/tests/testcases/quoted-key.yml
Labels: refactor

#826 chore(deps): `cargo autoinherit`
  Cargo.toml
  crates/github-actions-expressions/README.md
  crates/yamlpath/Cargo.toml
  crates/yamlpath/README.md
Labels: chore, dependencies

#828 ci: experiment with a binary release build
  .cargo/config.toml
  .github/workflows/release-binaries.yml
  support/archive-release.sh
Labels: packaging, ci/cd

#830 refactor: bring in github-actions-models
  .github/workflows/release-support-crate.yml
  Cargo.lock
  Cargo.toml
  crates/github-actions-models/Cargo.toml
  crates/github-actions-models/LICENSE
  crates/github-actions-models/README.md
  crates/github-actions-models/src/action.rs
  crates/github-actions-models/src/common.rs
  crates/github-actions-models/src/common/expr.rs
  crates/github-actions-models/src/dependabot/mod.rs
  crates/github-actions-models/src/dependabot/v2.rs
  crates/github-actions-models/src/lib.rs
  crates/github-actions-models/src/workflow/event.rs
  crates/github-actions-models/src/workflow/job.rs
  crates/github-actions-models/src/workflow/mod.rs
  crates/github-actions-models/tests/sample-actions/gh-action-pip-audit.yml
  crates/github-actions-models/tests/sample-actions/gh-action-pypi-publish.yml
  crates/github-actions-models/tests/sample-actions/gh-action-sigstore-python.yml
  crates/github-actions-models/tests/sample-actions/no-input-output-descriptions.yml
  crates/github-actions-models/tests/sample-actions/setup-python.yml
  crates/github-actions-models/tests/sample-dependabot/v2/pip-audit.yml
  crates/github-actions-models/tests/sample-dependabot/v2/sigstore-python.yml
  crates/github-actions-models/tests/sample-workflows/adafruit-circuitpython-run-tests.yml
  crates/github-actions-models/tests/sample-workflows/false-condition.yml
  crates/github-actions-models/tests/sample-workflows/gh-action-sigstore-python-selftest.yml
  crates/github-actions-models/tests/sample-workflows/git-annex-built-windows.yaml
  crates/github-actions-models/tests/sample-workflows/guacsec-guac-ci.yml
  crates/github-actions-models/tests/sample-workflows/homebrew-core-automerge-triggers.yml
  crates/github-actions-models/tests/sample-workflows/homebrew-core-dispatch-rebottle.yml
  crates/github-actions-models/tests/sample-workflows/intel-llvm-sycl-linux-run-tests.yml
  crates/github-actions-models/tests/sample-workflows/issue-35.yml
  crates/github-actions-models/tests/sample-workflows/jazzband-tablib-docs-lint.yml
  crates/github-actions-models/tests/sample-workflows/letsencrypt-boulder-boulder-ci.yml
  crates/github-actions-models/tests/sample-workflows/mhils-workflows-python-deploy.yml
  crates/github-actions-models/tests/sample-workflows/openbao-openbao-test-go.yml
  crates/github-actions-models/tests/sample-workflows/pip-api-test.yml
  crates/github-actions-models/tests/sample-workflows/pip-audit-ci.yml
  crates/github-actions-models/tests/sample-workflows/pip-audit-scorecards.yml
  crates/github-actions-models/tests/sample-workflows/pwn-requests.yml
  crates/github-actions-models/tests/sample-workflows/pyca-cryptography-ci.yml
  crates/github-actions-models/tests/sample-workflows/pypi-attestations-release.yml
  crates/github-actions-models/tests/sample-workflows/reusable-workflow-unpinned.yml
  crates/github-actions-models/tests/sample-workflows/rnpgp-rnp-centos-and-fedora.yml
  crates/github-actions-models/tests/sample-workflows/runs-on-expr.yml
  crates/github-actions-models/tests/sample-workflows/runs-on-group-only.yml
  crates/github-actions-models/tests/sample-workflows/scalar-trigger-type.yml
  crates/github-actions-models/tests/sample-workflows/vil02-puzzle_generator-check_examples.yml
  crates/github-actions-models/tests/sample-workflows/zizmor-issue-646.yml
  crates/github-actions-models/tests/sample-workflows/zizmor-issue-650.yml
  crates/github-actions-models/tests/test_action.rs
  crates/github-actions-models/tests/test_dependabot_v2.rs
  crates/github-actions-models/tests/test_workflow.rs
Labels: refactor

#831 chore: prep prerelease v1.8.0-rc0
  Cargo.lock
  crates/zizmor/Cargo.toml
Labels: chore

#832 fix: don't use wildcards for in-workspace deps
  .github/workflows/release-binaries.yml
  Cargo.lock
  Cargo.toml
  crates/zizmor/Cargo.toml
Labels: bugfix, ci/cd

#833 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#834 fix(ci): tell gh release upload where to go
  .github/workflows/release-binaries.yml
  Cargo.lock
  crates/zizmor/Cargo.toml
Labels: bugfix, ci/cd

#835 chore: prep for release v1.8.0
  Cargo.lock
  crates/zizmor/Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#836 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#837 docs: mention GitHub release binaries
  docs/installation.md
Labels: documentation

#838 feat(cli): add completion generation support for nushell
  Cargo.lock
  Cargo.toml
  crates/zizmor/Cargo.toml
  crates/zizmor/src/main.rs
  crates/zizmor/src/models.rs
  docs/release-notes.md
  docs/snippets/help.txt
Labels: enhancement, cli

#841 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#842 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#845 chore(docs): update org for shortcut links
  mkdocs.yml
Labels: documentation, bugfix

#843 docs: describe installation of Chimera Linux package
  docs/installation.md
Labels: documentation, enhancement

#745 Extract context patterns from webhook schemata
  .github/workflows/codegen.yml
  .github/workflows/refresh-schemas.yml
  Cargo.lock
  Cargo.toml
  Makefile
  crates/github-actions-expressions/src/context.rs
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/Cargo.toml
  crates/zizmor/build.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_569.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_612_repro.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-12.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-13.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-3.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-6.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-7.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-8.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__github_output.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__obfuscation.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-10.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-2.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-3.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-4.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-5.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-6.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-7.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-8.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-9.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection.snap
  crates/zizmor/tests/integration/test-data/template-injection/patterns.yml
  docs/release-notes.md
  pyproject.toml
  support/context-capabilities.csv
  support/known-safe-contexts.txt
  support/webhooks-to-contexts.py
  uv.lock
Labels: enhancement

#851 chore(docs): swap colon to dot
  docs/usage.md
Labels: documentation

#850 docs: add alpine linux installation notes
  docs/installation.md
Labels: documentation, packaging

#852 chore(docs): fix typos
  docs/installation.md
Labels: documentation, chore

#849 feat: add CodeQL injection sink data
  .github/workflows/codegen.yml
  Makefile
  crates/zizmor/build.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-11.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-12.snap
  crates/zizmor/tests/integration/test-data/template-injection/codeql-sinks.yml
  crates/zizmor/tests/integration/test-data/template-injection/pwsh-script.yml
  docs/release-notes.md
  pyproject.toml
  support/codeql-injection-sinks.json
  support/codeql-injection-sinks.py
  uv.lock
Labels: enhancement

#856 Update usage directions to explicitly state permissions needed
  docs/usage.md
Labels: documentation

#861 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#863 fix: update error message to handle enterprise servers
  crates/zizmor/src/main.rs
  docs/release-notes.md
Labels: cli, bugfix

#869 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#875 chore(docs): update sponsors
  README.md
  docs/snippets/render-sponsors.py
  docs/snippets/sponsors.html
  docs/snippets/sponsors.json
Labels: documentation, chore

#878 chore: release github-actions-expressions 0.0.4
  Cargo.lock
  Cargo.toml
  crates/github-actions-expressions/Cargo.toml
Labels: chore

#877 chore: prep for 1.9.0 release
  Cargo.lock
  Makefile
  crates/zizmor/Cargo.toml
  crates/zizmor/build.rs
  crates/zizmor/data/codeql-injection-sinks.json
  crates/zizmor/data/context-capabilities.csv
  docs/release-notes.md
  docs/usage.md
  support/webhooks-to-contexts.py
Labels: blocked, chore

#879 chore(ci): Small improvements around linting
  .github/workflows/ci.yml
  Cargo.toml
  crates/github-actions-expressions/Cargo.toml
  crates/github-actions-models/Cargo.toml
  crates/yamlpath/Cargo.toml
  crates/zizmor/Cargo.toml
Labels: chore, ci/cd

#858 Foundations of the Auto-Fix Feature
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/finding/mod.rs
  crates/zizmor/src/fix.rs
  crates/zizmor/src/main.rs
  crates/zizmor/src/yaml_patch/mod.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-8.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs.snap
Labels: enhancement, cli

#882 chore(ci): fix version variable in wolfi-update-check.sh
  support/wolfi-update-check.sh
Labels: chore, bugfix, ci/cd
