Repository zizmorcore/zizmor, pull requests merged in 2025-10, with the labels that each got.

#1203 docs: fix incorrect example highlighting and improve wording
  docs/audits.md
Labels: documentation

#1204 deps: move from tower-lsp to tower-lsp-server
  Cargo.lock
  Cargo.toml
  crates/zizmor/Cargo.toml
  crates/zizmor/src/lsp.rs
Labels: dependencies, language-server

#1211 github-actions-models: remove token from vendored testcase
  crates/github-actions-models/tests/sample-workflows/rnpgp-rnp-centos-and-fedora.yml
Labels: chore

#1205 Add Fix for ref-version-mismatch audit rule
  crates/zizmor/src/audit/ref_version_mismatch.rs
  crates/zizmor/src/main.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__ref_version_mismatch.snap
  docs/release-notes.md
Labels: enhancement, autofix

#1214 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, no-benchmark

#1220 feat: dependabot-execution audit
  crates/zizmor/src/audit/dependabot_execution.rs
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/models/dependabot.rs
  crates/zizmor/src/registry.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__dependabot_execution.snap
  crates/zizmor/tests/integration/test-data/dependabot-execution/basic/dependabot.yml
  docs/audits.md
  docs/usage.md
Labels: new-audit
