Repository zizmorcore/zizmor, pull requests merged in 2025-01, with the labels that each got.

#374 docs: move changelog to website
  .github/release.yml
  docs/limitations.md
  docs/release-notes.md
  docs/usage.md
  mkdocs.yml
Labels: documentation, chore

#375 chore: prep 1.0.0
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#376 chore: clean up changelog
  docs/release-notes.md
Labels: chore

#377 docs: README: remove beta warning
  README.md
Labels: documentation, chore

#382 docs: update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#383 refactor: CacheAwareAction -> UsesCoordinate
  src/audit/cache_poisoning.rs
  src/models.rs
  src/models/coordinate.rs
Labels: refactor

#388 deps: bump github-actions-models
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
Labels: bugfix

#386 refactor: generalize coordinate usage semantics
  src/audit/cache_poisoning.rs
  src/models.rs
  src/models/coordinate.rs
Labels: refactor

#389 fix: cache-poisoning: handle non-pushing docker-push-action
  docs/release-notes.md
  src/audit/cache_poisoning.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__cache_poisoning-14.snap
  tests/test-data/cache-poisoning/issue-378-repro.yml
Labels: bugfix

#391 feat: github-env audit checks GITHUB_PATH too
  docs/audits.md
  docs/release-notes.md
  src/audit/github_env.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__github_env-2.snap
  tests/snapshots/snapshot__github_env.snap
  tests/test-data/github-env/github-path.yml
Labels: enhancement

#392 docs: compress trophies
  docs/snippets/render-trophies.py
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#402 fix: template-injection: github.action_path is safe
  docs/release-notes.md
  src/audit/github_env.rs
  src/audit/template_injection.rs
  src/models/coordinate.rs
Labels: bugfix

#403 fix: handle non-trivial shells in github-env
  docs/release-notes.md
  src/audit/github_env.rs
  src/models.rs
  src/utils.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__github_env-3.snap
  tests/test-data/github-env/issue-397-repro.yml
Labels: bugfix

#404 docs: usage: clarify optional configuration
  docs/usage.md
Labels: documentation, chore

#406 chore: prep 1.0.1
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#407 docs: update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#408 feat: secrets-inherit: new audit
  docs/audits.md
  docs/release-notes.md
  src/audit/mod.rs
  src/audit/secrets_inherit.rs
  src/main.rs
  src/models.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__secrets_inherit.snap
  tests/test-data/secrets-inherit.yml
Labels: enhancement

#410 docs: update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#412 fix: template-injection: github.server_url is safe
  docs/release-notes.md
  src/audit/template_injection.rs
Labels: false-positive, bugfix

#413 docs: add another cache-poisoning resource
  docs/audits.md
Labels: documentation

#414 docs: update trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#416 docs: more trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#419 fix: update to use static link for PyPI display
  README.md
Labels: documentation

#420 fix: template-injection: do not fail on `uses:` steps
  .github/workflows/ci.yml
  docs/release-notes.md
  src/models.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__template_injection-7.snap
  tests/test-data/template-injection/issue-418-repro.yml
Labels: bugfix

#421 feat: template-injection: handle 2 more sinks
  docs/release-notes.md
  src/audit/template_injection.rs
Labels: enhancement

#422 docs: fix formatting
  docs/usage.md
Labels: documentation

#423 chore(docs): bump trophies, add arch install section
  docs/installation.md
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#424 refactor: UsesCoordinate -> ActionCoordinate
  src/audit/cache_poisoning.rs
  src/models/coordinate.rs
Labels: refactor

#426 chore: move tests
  src/models.rs
  src/models/uses.rs
Labels: chore

#428 chore: prep 1.1.0
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#430 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#437 fix: bump github-actions-models
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
Labels: bugfix

#438 chore: prep 1.1.1
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#439 fix: don't flag local workflows in unpinned-uses
  docs/release-notes.md
  src/audit/unpinned_uses.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__unpinned_uses-4.snap
  tests/test-data/unpinned-uses/issue-433-repro.yml
Labels: bugfix

#440 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#443 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#444 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#445 bugfix: mark another context as safe during injections
  docs/release-notes.md
  src/audit/template_injection.rs
Labels: false-positive, bugfix

#446 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
  src/registry.rs
Labels: documentation, chore

#448 fix: artipacked: check for stringy bools
  docs/release-notes.md
  src/audit/artipacked.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__artipacked-4.snap
  tests/test-data/artipacked/issue-447-repro.yml
Labels: false-positive, bugfix

#449 refactor: reduce invalid states in job APIs
  src/audit/artipacked.rs
  src/audit/cache_poisoning.rs
  src/audit/excessive_permissions.rs
  src/audit/github_env.rs
  src/audit/hardcoded_container_credentials.rs
  src/audit/impostor_commit.rs
  src/audit/insecure_commands.rs
  src/audit/mod.rs
  src/audit/ref_confusion.rs
  src/audit/secrets_inherit.rs
  src/audit/self_hosted_runner.rs
  src/audit/template_injection.rs
  src/config.rs
  src/finding/mod.rs
  src/main.rs
  src/models.rs
  src/models/coordinate.rs
  src/registry.rs
  src/render.rs
Labels: refactor

#450 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#451 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#453 bugfix: sarif: use absolute physical locations only
  docs/release-notes.md
  src/main.rs
  src/registry.rs
  src/sarif.rs
Labels: bugfix

#456 docs: typo
  docs/audits.md
Labels: documentation

#460 feat: bot-conditions
  docs/audits.md
  docs/release-notes.md
  src/audit/bot_conditions.rs
  src/audit/mod.rs
  src/main.rs
  src/models.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__bot_conditions.snap
  tests/test-data/bot-conditions.yml
Labels: enhancement

#461 bugfix: parse multi-line expressions correctly
  docs/release-notes.md
  src/expr/expr.pest
  src/expr/mod.rs
Labels: bugfix

#463 bugfix: bump github-actions-models
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
Labels: bugfix

#464 chore: prep 1.2.0
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#465 chore: remove site-requirements.txt
  Makefile
  pyproject.toml
  site-requirements.txt
Labels: documentation, chore

#469 bugfix: generalize path prefix handling
  docs/release-notes.md
  src/audit/bot_conditions.rs
  src/main.rs
  src/models.rs
  src/registry.rs
  src/render.rs
  src/sarif.rs
Labels: bugfix

#470 chore: prep 1.2.1
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#473 bugfix: special-case workflow_call in excessive-permissions
  .github/workflows/zizmor.yml
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  src/audit/excessive_permissions.rs
  src/models.rs
  src/registry.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__excessive_permissions-10.snap
  tests/snapshots/snapshot__excessive_permissions-11.snap
  tests/snapshots/snapshot__excessive_permissions-12.snap
  tests/test-data/excessive-permissions/issue-472-repro.yml
  tests/test-data/excessive-permissions/reusable-workflow-call.yml
  tests/test-data/excessive-permissions/reusable-workflow-other-triggers.yml
Labels: bugfix

#475 feat: improve error message when repo fetch fails
  docs/release-notes.md
  src/github_api.rs
  src/main.rs
Labels: enhancement

#476 chore: prep for 1.2.2 release
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#477 bugfix: collect actions from subdirectories of .github/workflows
  docs/release-notes.md
  src/main.rs
Labels: bugfix

#481 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#482 feat: improve parse error slightly
  docs/release-notes.md
  src/registry.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__invalid_inputs.snap
  tests/test-data/invalid/invalid-workflow.yml
Labels: enhancement

#484 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#486 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#487 deps: bump github-actions-models
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
Labels: bugfix, dependencies

#488 cli: reduce warning to info when skipping audits
  src/main.rs
Labels: enhancement

#485 feat: "raw" audit support + `overprovisioned-secrets`
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  docs/audits.md
  src/audit/mod.rs
  src/audit/overprovisioned_secrets.rs
  src/audit/template_injection.rs
  src/finding/locate.rs
  src/finding/mod.rs
  src/main.rs
  src/models.rs
  src/render.rs
  src/utils.rs
  tests/snapshot.rs
  tests/snapshots/snapshot__overprovisioned_secrets.snap
  tests/test-data/overprovisioned-secrets.yml
Labels: enhancement, new-audit

#489 release-notes: record #485
  docs/release-notes.md
Labels: documentation, chore

#490 feat(cli): add naches mode
  docs/release-notes.md
  src/main.rs
  src/render.rs
Labels: enhancement, cli

#491 refactor: improve context handling
  docs/release-notes.md
  src/audit/bot_conditions.rs
  src/audit/overprovisioned_secrets.rs
  src/audit/template_injection.rs
  src/expr/mod.rs
Labels: enhancement, refactor

#494 ci: attempt to fix arm build
  .github/workflows/pypi.yml
Labels: chore

#495 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#496 Downgrade tracing-indicatif
  Cargo.lock
  Cargo.toml
Labels: dependencies

#498 deps: bump indicatif from 0.17.9 to 0.17.11
  Cargo.lock
  Cargo.toml
Labels: dependencies

#499 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#500 chore: prep for 1.3.0 release
  Cargo.lock
  Cargo.toml
  docs/release-notes.md
  docs/usage.md
Labels: chore

#503 docs: bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#505 docs: update dev-docs
  docs/development.md
Labels: documentation
