Repository zizmorcore/zizmor, pull requests merged in 2025-08, with the labels that each got.

#1053 feat: new audit: unsound-condition
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/audit/obfuscation.rs
  crates/zizmor/src/audit/overprovisioned_secrets.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/unredacted_secrets.rs
  crates/zizmor/src/audit/unsound_condition.rs
  crates/zizmor/src/audit/unsound_contains.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/src/registry.rs
  crates/zizmor/src/utils.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unsound_condition.snap
  crates/zizmor/tests/integration/test-data/unsound-condition.yml
  docs/audits.md
  docs/release-notes.md
Labels: enhancement, new-audit

#1056 chore: add TODO
  crates/zizmor/src/audit/use_trusted_publishing.rs
Labels: chore, no-benchmark

#1059 feat: another template injection sink
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/tests/integration/test-data/template-injection/addnab-docker-run-action.yml
  docs/release-notes.md
Labels: enhancement

#1060 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore, no-benchmark

#1061 fix: fix overcorrected env patch for template-injection
  crates/zizmor/src/audit/template_injection.rs
  docs/release-notes.md
Labels: bugfix, autofix

#1064 Detect `shell` before applying template expression fixes
  crates/zizmor/src/audit/github_env.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/audit/use_trusted_publishing.rs
  crates/zizmor/src/models.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/src/models/workflow.rs
  docs/release-notes.md
Labels: bugfix

#1068 chore(docs): fix indentation in workflow samples
  docs/audits.md
Labels: documentation, chore, no-benchmark

#1073 chore: prep for release v1.12.0
  Cargo.lock
  crates/zizmor/Cargo.toml
  docs/integrations.md
  docs/release-notes.md
Labels: chore, no-benchmark

#1079 fix(ci): fix release-binaries workflow
  .github/workflows/release-binaries.yml
Labels: bugfix, ci/cd, no-benchmark

#1082 fix: flip setup-uv coordinate toggle
  crates/zizmor/src/audit/cache_poisoning.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-16.snap
  crates/zizmor/tests/integration/test-data/cache-poisoning/issue-1081-repro.yml
  docs/release-notes.md
Labels: bugfix

#1083 chore: prep release v1.12.1
  Cargo.lock
  crates/github-actions-models/src/workflow/job.rs
  crates/yamlpatch/src/lib.rs
  crates/zizmor/Cargo.toml
  crates/zizmor/src/audit/hardcoded_container_credentials.rs
  docs/integrations.md
  docs/release-notes.md
Labels: chore, no-benchmark

#1084 chore(ci): bump wolfi update check frequency
  .github/workflows/wolfi-update-check.yml
Labels: chore, ci/cd, no-benchmark

#1087 Document that composite action findings can be ignored with comments
  docs/configuration.md
Labels: documentation

#1091 refactor: give input registry APIs their own mod
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/cache_poisoning.rs
  crates/zizmor/src/audit/insecure_commands.rs
  crates/zizmor/src/audit/known_vulnerable_actions.rs
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/src/github_api.rs
  crates/zizmor/src/lsp.rs
  crates/zizmor/src/main.rs
  crates/zizmor/src/models/action.rs
  crates/zizmor/src/models/coordinate.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/src/output/fix.rs
  crates/zizmor/src/output/plain.rs
  crates/zizmor/src/registry.rs
  crates/zizmor/src/registry/input.rs
  crates/zizmor/src/utils.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_input_not_strict-2.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_input_not_strict.snap
Labels: refactor

#1093 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore, no-benchmark

#1092 refactor: add groups to the input registry
  crates/zizmor/src/audit/artipacked.rs
  crates/zizmor/src/audit/bot_conditions.rs
  crates/zizmor/src/audit/cache_poisoning.rs
  crates/zizmor/src/audit/insecure_commands.rs
  crates/zizmor/src/audit/known_vulnerable_actions.rs
  crates/zizmor/src/audit/template_injection.rs
  crates/zizmor/src/github_api.rs
  crates/zizmor/src/lsp.rs
  crates/zizmor/src/main.rs
  crates/zizmor/src/models/coordinate.rs
  crates/zizmor/src/models/workflow.rs
  crates/zizmor/src/output/plain.rs
  crates/zizmor/src/registry/input.rs
  crates/zizmor/src/utils.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_726.snap
Labels: refactor

#1102 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore, no-benchmark

#1104 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore, no-benchmark

#1105 Document that json-v1 uses 0-based line numbers
  docs/usage.md
Labels: documentation

#1103 chore(docs): `make pinact`
  .github/pinact.yml
  docs/integrations.md
  mise.toml
Labels: documentation, chore, no-benchmark

#1108 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore, no-benchmark

#1119 chore(docs): bump trophies
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore, no-benchmark

#1120 fix(docs): fix misleading dangerous-triggers docs
  docs/audits.md
Labels: documentation, no-benchmark

#1122 fix: respect --strict-collection for remote inputs
  crates/zizmor/src/github_api.rs
  crates/zizmor/src/registry/input.rs
  crates/zizmor/tests/integration/e2e.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_1116_strict_collection_remote_input-2.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_1116_strict_collection_remote_input.snap
  docs/release-notes.md
Labels: cli, bugfix
