Repository zizmorcore/zizmor, pull requests merged in 2025-09, with the labels that each got.

#1124 Add WordPress to the trophy list
  docs/snippets/trophies.md
  docs/snippets/trophies.txt
Labels: documentation, chore

#1132 feat: allow audits to be disabled in config
  crates/zizmor/src/audit/known_vulnerable_actions.rs
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/config.rs
  crates/zizmor/src/lsp.rs
  crates/zizmor/src/main.rs
  crates/zizmor/tests/integration/config.rs
  crates/zizmor/tests/integration/snapshots/integration__config__disablement.snap
  crates/zizmor/tests/integration/test-data/config-scenarios/disablement/.github/workflows/hackme.yml
  crates/zizmor/tests/integration/test-data/config-scenarios/disablement/zizmor.yml
  docs/configuration.md
  docs/release-notes.md
Labels: enhancement, config

#1133 chore(docs): document when audit disablement was added
  docs/configuration.md
Labels: documentation, chore, no-benchmark

#1134 chore(tests): add testcases for #742
  crates/zizmor/tests/integration/snapshots/integration__snapshot__unsound_condition.snap
  crates/zizmor/tests/integration/test-data/unsound-condition.yml
Labels: tests, chore

#1167 docs: bump sponsors list
  README.md
  docs/snippets/sponsors.html
  docs/snippets/sponsors.json
Labels: documentation, no-benchmark

#972 feat: new audit: ref-version-mismatch
  crates/zizmor/src/audit/mod.rs
  crates/zizmor/src/audit/ref_version_mismatch.rs
  crates/zizmor/src/finding/location.rs
  crates/zizmor/src/github_api.rs
  crates/zizmor/src/registry.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_1065.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_569.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__issue_726.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__menagerie-2.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__menagerie.snap
  crates/zizmor/tests/integration/snapshots/integration__e2e__pr_960_backstop.snap
  crates/zizmor/tests/integration/snapshots/integration__snapshot__ref_version_mismatch.snap
  crates/zizmor/tests/integration/test-data/ref-version-mismatch.yml
  docs/release-notes.md
Labels: new-audit

#1178 fix(obfuscation): don't consider fromJSON(...) constant-reducible
  crates/github-actions-expressions/src/lib.rs
  crates/zizmor/tests/integration/snapshot.rs
  crates/zizmor/tests/integration/snapshots/integration__snapshot__obfuscation-3.snap
  crates/zizmor/tests/integration/test-data/obfuscation/issue-1177-repro.yml
  docs/release-notes.md
Labels: bugfix

#1179 docs: document `ref-version-mismatch` audit
  docs/audits.md
  docs/release-notes.md
Labels: documentation

#1185 prep 1.14.1
  Cargo.lock
  crates/zizmor/Cargo.toml
  docs/integrations.md
  docs/release-notes.md
Labels: no-benchmark

#1193 prep release 1.14.2
  Cargo.lock
  crates/zizmor/Cargo.toml
  docs/integrations.md
  docs/release-notes.md
Labels: no-benchmark

#1200 perf: use jemalloc as the global allocator on non-Windows
  Cargo.lock
  Cargo.toml
  crates/zizmor/Cargo.toml
  crates/zizmor/src/main.rs
  docs/release-notes.md
Labels: enhancement, performance

#1201 fix: only use jemalloc on supported platforms
  crates/zizmor/src/main.rs
Labels: ci/cd
